title: SAHIL KOMMALAPATI
show_downloads: True
google_analytics:
theme: jekyll-theme-minimal
logo: /images/IMG_20191213_182941.jpg
logo1: /images/Isopoly_01.gif
github:
  zip_url: https://scholar.google.co.in/citations?hl=en&user=QqqnDkYAAAAJ
  tar_url: https://www.linkedin.com/in/kommalapati/
  git_url_: https://github.com/kommalapatisahil
  medium_url: https://medium.com/@kommalapatisahil
  resume_url: https://github.com/kommalapatisahil/bio/blob/master/CV_SK.pdf
  RG_url: https://www.researchgate.net/profile/Sahil_Kommalapati
  
